# Generated by Django 6.0.6 on 2026-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='issued_books'),
        ),
    ]
