# Generated by Django 6.0.6 on 2026-06-23 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_issuebook_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
            ],
        ),
    ]
