# Generated by Django 6.0.6 on 2026-06-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_returnbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='issue_date',
        ),
    ]
