# Generated by Django 6.0.6 on 2026-06-25 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_purchasebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebook',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
