# Generated by Django 6.0.6 on 2026-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_purchasebook_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebook',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
